---
# Task file for kubernetes master

- name: "install kubernetes"
  yum:
      name: "{{ packages }}" 
      state: "present"
  vars:
      packages:
      - "kubectl-1.15.3-0"
      - "kubeadm-1.15.3-0"


- name: Create a 2048-bit SSH key for user {{ kubeacc }} 
  user:
    name: "{{ kubeacc }}"

- name: "initialize the cluster"
  shell: kubeadm init --pod-network-cidr=192.168.0.0/16 >> cluster_initialized.txt
  args:
    chdir: $HOME
    creates: cluster_initialized.txt

- name: create .kube directory
  become: yes
  become_user: "{{ kubeacc }}"
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ kubeacc }}/.kube/config
    remote_src: yes
    owner: "{{ kubeacc }}"

- name: install Pod network
  become: yes
  become_user: "{{ kubeacc }}"
  shell: kubectl apply -f https://docs.projectcalico.org/v3.9/manifests/calico.yaml >> pod_network_setup.txt
  args:
    chdir: $HOME
    creates: pod_network_setup.txt

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"