---
# Task file for kubernetes common

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: "installing yum packages"
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - docker

- name: "start Docker"
  service:
    name: docker
    state: started
    enabled: yes

- name: "reload sysctl"
  sysctl:
      name: "{{ item.name }}"
      value: "{{ item.value }}"
      reload: yes
  with_items:
      - {name: "net.bridge.bridge-nf-call-ip6tables", value: "1"}
      - {name: "net.bridge.bridge-nf-call-iptables", value: "1"}

- name: add Kubernetes' YUM repository
  yum_repository:
    name: Kubernetes
    description: Kubernetes YUM repository
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: yes

- name: "installing yum package"
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - kubelet

- name: "start kubelet"
  service:
    name: kubelet
    state: started
    enabled: yes